import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import ReactQueryProvider from "@/query/ReactQueryProvider";
import { ContextProvider } from "@/contexxt/Context";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "GreenShop",
  description: "Generated by create next app",

};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} pt-[25px] w-[1200px] mx-auto antialiased`}
      >
        <ReactQueryProvider >
          <ContextProvider>
            <Header />
            <Toaster position="top-center" reverseOrder={false} />
            {children}
            <Footer />
          </ContextProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
